dj_elastic_search/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("posts.urls")),
]

posts/urls.py
from django.urls import path

from posts.views import home, create_post, save_post

app_name = "posts"

urlpatterns = [
    path("", home, name="index"),
    path("create", create_post, name="create"),
    path("save", save_post, name="save"),
]

posts/models.py
from django.db import models
from django.utils import timezone

from posts.es_search import PostDocument


class Post(models.Model):
    title = models.CharField(max_length=250)
    body = models.TextField()
    posted_date = models.DateField(default=timezone.now)

    def __str__(self):
        return self.title

    def indexing(self):
        obj = PostDocument(
            meta={'id': self.id},
            posted_date=self.posted_date,
            title=self.title,
            body=self.body
        )
        obj.save()
        return obj.to_dict(include_meta=True)

posts/views.py
from django.shortcuts import render, redirect, reverse
from elasticsearch_dsl import Search

from posts.models import Post


def home(request):
    search = Search(index="post_index")
    result = search.execute()
    data = result.hits
    return render(request, 'index.html', {'posts': data})


def create_post(request):
    return render(request, 'create.html')


def save_post(request):
    title = request.POST.get('title')
    body = request.POST.get('body')
    post = Post.objects.create(title=title, body=body)
    post.indexing()
    return redirect(reverse('posts:index'))

templates/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create post</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
</head>
<body>


<div class="container">
    <div class="row">
        <div class="col-md-12">
            <a href="{% url 'posts:index' %}" class="btn btn-primary text-right">Back</a>
            <form action="{% url 'posts:save' %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="title">Post title</label>
                    <input type="text" class="form-control" placeholder="title" id="title" name="title">
                </div>
                <div class="form-group">
                    <label for="body">Post body</label>
                    <textarea name="body" id="body" cols="30" rows="10" class="form-control"></textarea>
                </div>
                <button type="submit" class="btn btn-success pull-right">Save</button>
            </form>
        </div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js"></script>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>All posts</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
</head>
<body>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <a href="{% url 'posts:create' %}" class="btn btn-primary text-right">Create post</a>

            <table class="table">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Title</th>
                    <th scope="col">Body</th>
                    <th scope="col">Posted date</th>
                </tr>
                </thead>
                <tbody>
                {% for post in posts %}
                    <tr>
                        <th scope="row">{{ post.meta.id }}</th>
                        <td>{{ post.title }}</td>
                        <td>{{ post.body }}</td>
                        <td>{{ post.posted_date }}</td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js"></script>
</body>
</html>